### PR TITLE
Show marker at 'Close To...' location

### PR DESCRIPTION
**Pull request by woeltjen**
## Description
Continuing with search filters: Show a marker at the user's chosen 'Close To...' location

## How to Test
1. Search
2. Click 'Close To...'
3. Select some place on your map
4. Verify that labelled marker shows up at that place

Which devices did you test on?
- [ ] Chrome on Mac
- [ ] Chrome on PC
- [ ] Firefox on Mac
- [ ] Firefox on PC
- [ ] Safari iPhone
- [ ] Chrome Android

## REVIEWERS:
Check against these principles:

### High level
Does this code need to be written?
What are the alternatives?
Will this implementation become a support issue?
How much error margin does this solution have?

### Code
* Does the code follow industry standards?
JS: https://github.com/airbnb/javascript
React: https://github.com/airbnb/javascript/tree/master/react
https://github.com/vasanthk/react-bits
Documentation headers: http://usejsdoc.org/index.html

* Is there duplicated code? Can it be refactored into a shared method?
* Is the code consistent with our project?
* Are there unit tests? Do they test the states?
* Is the person refactoring another developer's code? If possible, did the original developer approve?

### Variables/Naming:
* Would the variable type led to future edge cases?
* Are the variable naming clear? Would the value contain something other than what the name describes.

### Security
* Can this be hacked or abused by the user?

## Further Work
1. Driving directions
2. Centering on pin
3. More filters

## Learnings
Looked at the "centering on pin" part, think that needs to be its own issue; correct behavior is non-obvious, as other variables including the search query's bounds and the locations of listings themselves need to be considered

### CODE REVIEW

**Comment by kcvan** [comment]
pin shows! is it possible to make the pin look like the red ones...but blue?  the pin and text were a little hard to find.  wondering if centering the map around the pin would be better ui?

@tommy-bee @jerminatorhits

**Comment by woeltjen** [comment]
Changing the color is unfortunately [non-trivial](https://stackoverflow.com/questions/2472957/how-can-i-change-the-color-of-a-google-maps-marker); we get to replace the whole icon or use their default, basically. Having our own icon image set would be nice.

Agree on centering; see notes under "Learnings".

**Comment by kcvan** [comment]
> Agree on centering; see notes under "Learnings".

ah! sorry i missed that. 👍

**Comment by kcvan** [comment]
>  Having our own icon image set would be nice.

time to get a bee svg

**Comment by kcvan** [comment]
https://iconmonstr.com/location-1-svg/ maybe?

**Comment by woeltjen** [comment]
> https://iconmonstr.com/location-1-svg/ maybe?

Ooh, I like! Filed #295 to look at icons separately; there were a couple in the same set as that one that looked promising to me

**Pull request merged**
