### PR TITLE
Move destination marker back to front

### PR DESCRIPTION
**Pull request by woeltjen**
## Description
#308 introduced a subtle regression: Pricing overlays obscure the destination marker, making it difficult to find (in some circumstances) even when it is in the map's bounds.

Root cause was the switch to "overlays" (which allow custom markup) from "markers" (which are just images or paths); the former exists on a separate layer from the latter. In particular, we need to use the `OVERLAY_MOUSE_TARGET` layer to support mouse interactions (clicking on pricing markers), but that layer is in front of the layer which displays markers (and the destination is still a marker)

Solution here is hacky: Move the pricing display to `OVERLAY_LAYER`, which appears below the marker layer. Then, to support mouse interactions, include a redundant set of overlays in the `OVERLAY_MOUSE_TARGET` layer with same properties but an opacity of `0`

## How to Test
1. Do a search
2. Choose a destination near many listings (e.g. Moscone Center)
3. Expect destination marker to obscure listings (and not the other way around)

Which devices did you test on?
- [x] Chrome on Mac
- [ ] Chrome on PC
- [ ] Firefox on Mac
- [ ] Firefox on PC
- [ ] Safari iPhone
- [ ] Chrome Android

## REVIEWERS:
Check against these principles:

### High level
Does this code need to be written?
What are the alternatives?
Will this implementation become a support issue?
How much error margin does this solution have?

### Code
* Does the code follow industry standards?
JS: https://github.com/airbnb/javascript
React: https://github.com/airbnb/javascript/tree/master/react
https://github.com/vasanthk/react-bits
Documentation headers: http://usejsdoc.org/index.html

* Is there duplicated code? Can it be refactored into a shared method?
* Is the code consistent with our project?
* Are there unit tests? Do they test the states?
* Is the person refactoring another developer's code? If possible, did the original developer approve?

### Variables/Naming:
* Would the variable type led to future edge cases?
* Are the variable naming clear? Would the value contain something other than what the name describes.

### Security
* Can this be hacked or abused by the user?

### CODE REVIEW

**Comment by kcvan** [comment]
i think there might be a missing `key={x}` on a map, getting:
```
Warning: Each child in a list should have a unique "key" prop.
```

**Comment by kcvan** [comment]
also just to be sure, the destination marker should be obscuring the listing prices, not necessarily the listing pop up card, right?

**Comment by woeltjen** [comment]
> also just to be sure, the destination marker should be obscuring the listing prices, not necessarily the listing pop up card, right?

Yep (think obscuring the listing pop up would look bad; think changing the opacity of the info window is the solution there)

**Comment by woeltjen** [comment]
> i think there might be a missing `key={x}` on a map, getting:

Ah, thanks! There were keys there, but they were in a `<></>` which seems to throw off React for whatever reason. Switched to two loops so that both could return arrays of single, keyed Elements, and the error went away.

**Pull request merged**
