### PR TITLE
Reposition carousel arrows

### PR DESCRIPTION
**Pull request by woeltjen**
## Description
Arrows on our carousel could be observed to sometimes disappear behind the image or misalign too far to the right, and to bounce around as image size changed. This positions both arrows consistently outside of the carousel photo area.

## How to Test
1. Navigate to a specific `/listings/:id`
2. Click View Photos
3. Click left and right to scroll through photos
4. Expect left/right arrows to remain in place and visible as photo dimensions change

Which devices did you test on?
- [x] Chrome on Mac
- [ ] Chrome on PC
- [ ] Firefox on Mac
- [ ] Firefox on PC
- [ ] Safari iPhone
- [ ] Chrome Android

## REVIEWERS:
Check against these principles:

### High level
Does this code need to be written?
What are the alternatives?
Will this implementation become a support issue?
How much error margin does this solution have?

### Code
* Does the code follow industry standards?
JS: https://github.com/airbnb/javascript
React: https://github.com/airbnb/javascript/tree/master/react
https://github.com/vasanthk/react-bits
Documentation headers: http://usejsdoc.org/index.html

* Is there duplicated code? Can it be refactored into a shared method?
* Is the code consistent with our project?
* Are there unit tests? Do they test the states?
* Is the person refactoring another developer's code? If possible, did the original developer approve?

### Variables/Naming:
* Would the variable type led to future edge cases?
* Are the variable naming clear? Would the value contain something other than what the name describes.

### Security
* Can this be hacked or abused by the user?

### CODE REVIEW

**Comment by kcvan** [comment]
i think something might have gotten introduced in a different pr but i cant click on the view photos button to get to the carousel

**Comment by woeltjen** [comment]
> i think something might have gotten introduced in a different pr but i cant click on the view photos button to get to the carousel

Are you looking at `/work/listings/:id` or just `/listings/:id`? This PR targets the latter (tho should get picked up by the former when #255 is merged)

**Comment by kcvan** [comment]
ah! my bad, will checkout `/listings/:id`

**Comment by kcvan** [comment]
everything looks good on desktop/tablet/mobile!  i think the only thing is that the arrows get lost on iPhone 5/SE

**Comment by woeltjen** [comment]
> i think the only thing is that the arrows get lost on iPhone 5/SE

Ah, nice catch! Marking WIP to fix that

**Pull request merged**
