### PR TITLE
add query params when conference clicks thru to hotel room

### PR DESCRIPTION
**Pull request by jerminatorhits**
## Description
Why did you write this code?
When a user is on the conference page and clicks a hotel, the calendar should autopopulate dates.

**Since Hotel Room `checkInDate` and `checkOutDate` are no longer hardset (we made them optional fields), we should populate with conference dates. Unsure if we should hold `Listings` on the conference page to the same rule because they are generally more flexible?

## How to Test
- [ ] Visit conferences/bee-con
- [ ] Click a Hotel Listing without declared start and end dates.
- [ ] Verify the calendar populates with conference dates.
- [ ] Click a Hotel Listing WITH declared dates
- [ ] Verify the calendar populates using the Hotel Listing Object's 'checkInDate' and 'checkOutDate' 

Which devices did you test on?
- [x] Chrome on Mac
- [ ] Chrome on PC
- [ ] Firefox on Mac
- [ ] Firefox on PC
- [ ] Safari iPhone
- [ ] Chrome Android

## REVIEWERS:
Check against these principles:

### High level
Does this code need to be written?
What are the alternatives?
Will this implementation become a support issue?
How much error margin does this solution have?

### Code
* Does the code follow industry standards?
JS: https://github.com/airbnb/javascript
React: https://github.com/airbnb/javascript/tree/master/react
https://github.com/vasanthk/react-bits
Documentation headers: http://usejsdoc.org/index.html

* Is there duplicated code? Can it be refactored into a shared method?
* Is the code consistent with our project?
* Are there unit tests? Do they test the states?
* Is the person refactoring another developer's code? If possible, did the original developer approve?

### Variables/Naming:
* Would the variable type led to future edge cases?
* Are the variable naming clear? Would the value contain something other than what the name describes.

### Security
* Can this be hacked or abused by the user?

## Further Work
Will this have future work?

## Learnings
Did you learn anything here you want to share with the team?

### CODE REVIEW

**Comment by kcvan** [comment]
@jerminatorhits can you tell me what days the conference with and without should default to?

**Comment by jerminatorhits** [comment]
@kcvan if there are no hardcoded dates on the hotel room listing itself, it will default to using conference dates.
if there are specified dates on the hotel listing itself, it will use those dates.

**Comment by kcvan** [comment]
should fix your test instructions to `* Verify the calendar populates with declared dates.` for the last box😉

**Comment by jerminatorhits** [comment]
o shoot. my b my b 😓

**Pull request merged**
