### PR TITLE
Remove 'express' from Stripe-related names

### PR DESCRIPTION
**Pull request by woeltjen**
## Description
As mentioned in [comments](https://github.com/thebeetoken/beenest-web/pull/102#discussion_r252459619) to #102, Stripe Express is (or has become) more specific than necessary when used in reference to Stripe accounts. This simplifies both file names and URLs.

Note that this has been branched from #102 and should be reviewed/merged thereafter

## How to Test
This is a refactor; should regression-test:

1. Creating a new Stripe account as a host
2. Connecting an existing Stripe account as a host

Which devices did you test on?
- [ ] Chrome on Mac
- [ ] Chrome on PC
- [ ] Firefox on Mac
- [ ] Firefox on PC
- [ ] Safari iPhone
- [ ] Chrome Android

## REVIEWERS:
Check against these principles:

### High level
Does this code need to be written?
What are the alternatives?
Will this implementation become a support issue?
How much error margin does this solution have?

### Code
* Does the code follow industry standards?
JS: https://github.com/airbnb/javascript
React: https://github.com/airbnb/javascript/tree/master/react
https://github.com/vasanthk/react-bits
Documentation headers: http://usejsdoc.org/index.html

* Is there duplicated code? Can it be refactored into a shared method?
* Is the code consistent with our project?
* Are there unit tests? Do they test the states?
* Is the person refactoring another developer's code? If possible, did the original developer approve?

### Variables/Naming:
* Would the variable type led to future edge cases?
* Are the variable naming clear? Would the value contain something other than what the name describes.

### Security
* Can this be hacked or abused by the user?

## Further Work
Think we have some `stripe_express` going on on the backend too...

### CODE REVIEW

**Comment by woeltjen** [comment]
@tommy-bee When self-testing, I run into:

    {
      "error": "invalid_redirect_uri",
      "error_description": "Invalid redirect URI 'http://localhost:4200/account/stripe/complete'. Ensure this uri exactly matches one of the uris specified in your application settings",
      "state": null
    }

`localhost` was previously working, so I think there's a configuration change needed Stripe-side to accept `/account/stripe/complete`

**Comment by tc** [comment]
yea, i added the new url handler; should work now.

**Comment by woeltjen** [comment]
Hm, still seeing that message; wonder if there's some delay before changes take effect...

**Comment by tc** [comment]
@woeltjen try now; i make it the default one.

as a bonus, it looks like this shows up the correct error message too(i didn't verify by stripe email)
```
There was an error.

The email you are trying to use is not valid.

There was an error processing your information. Please restart the sign up process by clicking the link from your email.
```

**Comment by woeltjen** [comment]
Still hitting that error; URL I'm trying is https://connect.stripe.com/oauth/authorize?redirect_uri=http://localhost:4200/account/stripe/complete&response_type=code&client_id=ca_CmC1grl4bBfjYWWwKg548UPazsb6USUW&scope=read_write

**Comment by tc** [comment]
sorry, try again now; i did `https` and was using the other PR

**Comment by woeltjen** [comment]
Working now! Thanks!

**Comment by tc** [comment]
@woeltjen can you add a link for "supported countries" to https://stripe.com/global

**Pull request merged**
