### PR TITLE
Show Carousel on View Photos

### PR DESCRIPTION
**Pull request by woeltjen**
## Description
Implement the View Photos button under the new design, this time using our existing carousel

## How to Test
1. View `/work/listings/:id` for some listing you like
2. Click "View Photos"
3. Expect photo carousel to appear full screen
4. Click X in top-right of photo carousel
5. Expect photo carousel to go away

Which devices did you test on?
- [x] Chrome on Mac
- [ ] Chrome on PC
- [ ] Firefox on Mac
- [ ] Firefox on PC
- [ ] Safari iPhone
- [ ] Chrome Android

## REVIEWERS:
Check against these principles:

### High level
Does this code need to be written?
What are the alternatives?
Will this implementation become a support issue?
How much error margin does this solution have?

### Code
* Does the code follow industry standards?
JS: https://github.com/airbnb/javascript
React: https://github.com/airbnb/javascript/tree/master/react
https://github.com/vasanthk/react-bits
Documentation headers: http://usejsdoc.org/index.html

* Is there duplicated code? Can it be refactored into a shared method?
* Is the code consistent with our project?
* Are there unit tests? Do they test the states?
* Is the person refactoring another developer's code? If possible, did the original developer approve?

### Variables/Naming:
* Would the variable type led to future edge cases?
* Are the variable naming clear? Would the value contain something other than what the name describes.

### Security
* Can this be hacked or abused by the user?

## Further Work
1. Booking Card functionality
2. And oof, this is a reminder that those left/right arrows are mispositioned; will hot fix that separately

## Learnings
After #240, I have a new appreciation for the fine art of giving up and starting over.

### CODE REVIEW

**Comment by kcvan** [comment]
a small issue with our old carousel, you cant click back on most of the photos (the image covers the button).  and even on some photos where the image isnt covering it, you cant click back

**Comment by kcvan** [comment]
oops i see your other pr, disregard last comment

**Comment by kcvan** [comment]
carousel works as normal!

**Comment by woeltjen** [comment]
> carousel works as normal!

I'll fix that in a subsequent PR 😀

**Pull request merged**
