### PR TITLE
Add travel mode selection

### PR DESCRIPTION
**Pull request by woeltjen**
## Description
This adds the ability to choose travel mode (from driving, transit, walking, and bicycling) when selecting a "Close To..." location

## How to Test
1. Make a search
2. Enter a "Close To..." location
3. Hover over some listings to view directions
4. Use "Close To..." drop down to change travel mode (e.g. to "walking")
5. Hover over more listings
6. Expect directions to change to fit the specified travel mode

Note that sometimes the visual difference between (e.g.) driving directions and walking can be subtle.

Which devices did you test on?
- [ ] Chrome on Mac
- [ ] Chrome on PC
- [ ] Firefox on Mac
- [ ] Firefox on PC
- [ ] Safari iPhone
- [ ] Chrome Android

## REVIEWERS:
Check against these principles:

### High level
Does this code need to be written?
What are the alternatives?
Will this implementation become a support issue?
How much error margin does this solution have?

### Code
* Does the code follow industry standards?
JS: https://github.com/airbnb/javascript
React: https://github.com/airbnb/javascript/tree/master/react
https://github.com/vasanthk/react-bits
Documentation headers: http://usejsdoc.org/index.html

* Is there duplicated code? Can it be refactored into a shared method?
* Is the code consistent with our project?
* Are there unit tests? Do they test the states?
* Is the person refactoring another developer's code? If possible, did the original developer approve?

### Variables/Naming:
* Would the variable type led to future edge cases?
* Are the variable naming clear? Would the value contain something other than what the name describes.

### Security
* Can this be hacked or abused by the user?

## Further Work
The full-page-reload which occurs on some destination changes becomes a bit more painful with this change, as it prevents the user from directly proceeding to selecting travel mode

### CODE REVIEW

**Comment by woeltjen** [comment]
Marking WIP while grumble grumble TypeScript

**Comment by kcvan** [comment]
i think the hovering of the card works really well!  

a ux experience i felt was that it does it a little confusing when i click on a listing on the map, then try and change the filter, the map doesn't update with new directions.  it also gets a little confusing when we have a listing clicked on the map and you move your mouse over to the filter and accidentally hover over another listing

**Comment by woeltjen** [comment]
> a ux experience i felt was that it does it a little confusing when i click on a listing on the map, then try and change the filter, the map doesn't update with new directions.

Ah, good catch, there was a check on `GoogleMapsWithMarkers` that was swallowing that change. Fixed; switching among driving options can be a nice use case!

> it also gets a little confusing when we have a listing clicked on the map and you move your mouse over to the filter and accidentally hover over another listing

Hm, that hurts the above use case. I've itemized that in the spreadsheet from earlier. Not sure what the fix would be; maybe require user to remain hovered for 150ms before changing selection?

**Comment by kcvan** [comment]
> Hm, that hurts the above use case. I've itemized that in the spreadsheet from earlier. Not sure what the fix would be; maybe require user to remain hovered for 150ms before changing selection?

this sounds like a solid fix!

**Comment by kcvan** [comment]
> Ah, good catch, there was a check on GoogleMapsWithMarkers that was swallowing that change. Fixed; switching among driving options can be a nice use case!

works great!

**Pull request merged**
