### PR TITLE
kevin/legacy-deprecation-#1

### PR DESCRIPTION
**Pull request by kcvan**
## Description
Why did you write this code?
start legacy deprecation
## How to Test
- [ ] Visit beenest
- [ ] verify site still works

Which devices did you test on?
- [x] Chrome on Mac
- [ ] Chrome on PC
- [ ] Firefox on Mac
- [ ] Firefox on PC
- [ ] Safari iPhone
- [ ] Chrome Android

## REVIEWERS:
Check against these principles:

### High level
Does this code need to be written?
What are the alternatives?
Will this implementation become a support issue?
How much error margin does this solution have?

### Code
* Does the code follow industry standards?
JS: https://github.com/airbnb/javascript
React: https://github.com/airbnb/javascript/tree/master/react
https://github.com/vasanthk/react-bits
Documentation headers: http://usejsdoc.org/index.html

* Is there duplicated code? Can it be refactored into a shared method?
* Is the code consistent with our project?
* Are there unit tests? Do they test the states?
* Is the person refactoring another developer's code? If possible, did the original developer approve?

### Variables/Naming:
* Would the variable type led to future edge cases?
* Are the variable naming clear? Would the value contain something other than what the name describes.

### Security
* Can this be hacked or abused by the user?

## Further Work
Will this have future work?

## Learnings
Did you learn anything here you want to share with the team?

### CODE REVIEW

**Comment by kcvan** [comment]
i've been running into this circleci issue every since we started our rebrand...
```
ERROR in ./src/pages/App.tsx
Module not found: Error: Can't resolve './account' in '/home/circleci/repo/src/pages'
 @ ./src/pages/App.tsx 11:0-32 66:973-980
 @ ./src/pages/index.ts
 @ ./src/index.tsx

ERROR in [at-loader] ./src/pages/App.tsx:9:21 
    TS2307: Cannot find module './account'.
```

the weird thing is that it's found locally, and it works fine.  I changed the page name from `Account` to `account` to match our folder names and this issue won't go away until i change it back to `Account`.
Any ideas?

**Comment by tc** [comment]
@kcvan it's most likely the case sensitivity difference between Mac / Linux so double check you renamed it on the Mac to lower case.

**Comment by kcvan** [comment]
is there a solid way of making sure the name has been changed? it looks like on github it shows `Account` but on my local it shows it as `account`
Screen Shot 2019-03-24 at 9 47 50 PM
Screen Shot 2019-03-24 at 9 48 00 PM

**Comment by kcvan** [comment]
doesn't seem like git is recognizing the folder name change as a diff, will research more

**Comment by kcvan** [comment]
if anyone was wondering, the way to do it was:
```
git mv Account tempname && git mv tempname account
```

src: https://www.patrick-wied.at/blog/rename-files-and-folders-with-git

under: **Renaming foldername to folderName on case insensitive file systems**

**Pull request merged**
